[tool.black]
line-length = 120
target-version = ['py310']
include = ['\.pyi?$']

[tool.ruff]
line-length = 120  # needs to match black

[tool.mypy]
python_version = "3.10"

[[tool.mypy.overrides]]
module = 'fire'
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = 'any_serde'
ignore_missing_imports = true
